### ISSUE TITLE
Ruby 3.3.3

### ISSUE THREAD

**Issue by jgraichen** [maths22/deb-ruby#2]
Are there any plans for Ruby 3.3.3 since `bootsnap` does not work with `3.3.1`?

**Comment by maths22** [comment]
Thank you for pointing out that ruby 3.3.3 is out.  I'll get working on getting packages built now.

**Comment by maths22** [comment]
Both the code in the repository and the ruby3.3 deb available in the [ppa](https://launchpad.net/~instructure/+archive/ubuntu/ruby) have now been updated to 3.3.3

**Comment by jgraichen** [comment]
Thank you so much! 

I tried updating on my own, but at least the gbp configuration for uscan didn't match the existing branches, and I had no idea how you import new upstream releases. Thanks for updating!

**Comment by maths22** [comment]
Yeah, it's a pain.  I now see I had a super outdated wiki because I had put our new documentation in our internal wiki instead.  I've moved it here https://github.com/instructure/deb-ruby/wiki#new-minor-version so that you (or anyone else) can see it, but actually performing most of the steps requires push access to this repository and access to our launchpad account for the PPA parts.
